### ISSUE TITLE
left_personality_trait and right_personality_trait not documented

### ISSUE THREAD

**Issue by fredngo** [traitify/traitify-ruby#1]
Hello,

I am trying to use this gem as specified in the README:

``` ruby
traits = traitify.assessment_personality_traits("assessment-uuid")
trait = traits.first
trait.score #=> 100
personality_trait = trait.personality_trait
personality_trait.name        #=> "Imaginative"
personality_trait.definition  #=> "Able to think symbolically and play with ideas."
personality_trait.description #=> "Coming Soon"
```

However, I get:

``` ruby
traits = traitify.assessment_personality_traits("assessment-uuid")
trait = traits.first
trait.score #=> -100.0
personality_trait = trait.personality_trait #=> nil 
```

It looks like the `personality_trait` method no longer exists. Looking further into `trait` I see that now there are now `left_personality_trait`, `right_personality_trait` methods, and a `score` method that returns a score from `-100.0` to `100.0`.

Am I correct to assume that if the score is negative, then it is correlated with the `left_personality_trait`, while if the score is positive, then it is correlated with the `right_personality_trait`?

Can the `README` be updated to reflect these changes and what `left_personality_trait` and `right_personality_trait` mean?

Thanks.

**Comment by efleming** [comment]
Changed method name in commit https://github.com/traitify/traitify-ruby/commit/55b0e4c2dda3b568ece4956baa2d0a64a5367501, will update later to show documentation for left and right personality traits.
