### ISSUE TITLE
Personality Traits returned by traitify-ruby not the same as those returned by traitify-js-widgets

### ISSUE THREAD

**Issue by fredngo** [traitify/traitify-ruby#2]
For reference, the assessment UUID used in this scenario is `6d28f34b-af14-4fbe-b774-f321fadb5092`, created on the `https://api-sandbox.traitify.com` host.

On the backend, the UUID is saved to database. On the frontend, I am using the `traitify-js-widgets` library to create the slide deck on the front end for the user to go through. After the user finishes the assessment, he is presented with his assessed personality traits using the `Traitify.ui.load("personalityTraits", assessmentId, ".traitify-widget");` call.

![traits](https://cloud.githubusercontent.com/assets/11791/7808845/a8fd94ee-03c8-11e5-8666-af75e16579d9.png)

Now, I use `traitify-ruby` on the backend to get the personality traits of the user with the following code:

``` ruby
traits = traitify.assessment_personality_traits "6d28f34b-af14-4fbe-b774-f321fadb5092"

traits.first(8).collect { |trait| [trait.left_personality_trait.name, trait.right_personality_trait.name, trait.score] }

#=> [
  ["Creative", "Uncreative", -100.0], 
  ["Reserved", "Sociable", -100.0], 
  ["Open-Minded", "Close-Minded", -74.46808], 
  ["Casual", "Formal", -63.636364], 
  ["Curious", "Disinterested", -60.714287], 
  ["Empathic", "Unempathic", -60.000004], 
  ["Focused", "Distractible", -58.441555], 
  ["Analytical", "Cursory", -56.521736]
] 
```

Leaving aside how to interpret `left_personality_trait`, `right_personality_trait` as raised in Issue https://github.com/traitify/traitify-ruby/issues/1, the results returned by `traitify-ruby` only somewhat correlates with the results from `traitify-js-widgets`, which are (as seen in `traits.png`): Creative, Sociable, Eclectic, Open-Minded, Rational, Intellectually-Driven, Casual, and Curious.

The following traits that are shown on the widget seem to be missing altogether from the first 8 traits: Eclectic, Rational, Intellectually-Driven.

I assume that both `traitify-ruby` and `traitify-js-widgets` are calling the same API to receive the assessed personality traits, so it puzzles me that the results are not the same.

Help? It is important for my application that these results remains consistent. Thank you.

**Comment by efleming** [comment]
Fred-

First of all, thanks for checking out Traitify. The js client makes a call to a different endpoint, the equivalent in this library is the call to `#raw_personality_traits` - https://github.com/traitify/traitify-ruby/blob/master/lib/traitify/client/results.rb#L24. Your code above could be 

```
traits = traitify.raw_personality_traits "6d28f34b-af14-4fbe-b774-f321fadb5092"
```

That will result in the same traits as the js client. The other call returns what is called a trait dichotomy and the score indicates which trait your personality reflects more in that dichotomy. A negative number reflects the left personality trait and a positive number reflects the right personality trait. We will update the documentation of the library to reflect these differences, I hope this helps.

**Comment by fredngo** [comment]
Holy smokes, thanks for the quick reply! I'll try out `raw_personality_traits`, thanks.

**Comment by efleming** [comment]
No problem, let me know if you have any further issues. I temporarily updated the README to reflect the change in method name. I'll update it later to document left and right personality trait. Thanks for bringing this to my attention.

**Comment by fredngo** [comment]
Thanks Eric. using `raw_personality_traits` does give me the same result as the widget.

``` ruby
traits.first(8).collect { |trait| [trait.personality_trait.name, trait.score] }
 => [["Creative", 100.0], ["Sociable", 100.0], ["Eclectic", 100.0], ["Open-Minded", 74.46808], ["Rational", 72.72727], ["Intellectually-Driven", 64.28571], ["Casual", 63.636364], ["Curious", 60.714287]] 
```

While I have you on the line, could you possibly explain to me what the colored bar at the top of the each personality in the widget means? In particular I'm wondering why Creative is green and Sociable is red, while each having a score of 100.0, and why Open-Minded (74.5) is Green and Rational (72.7) is Blue, when the scores are so similar.

Thanks!

**Comment by efleming** [comment]
Sure, there is a personality type associated with each trait. Each personality type has a badge and that badge has at least 1 color and 1 image associated with it. 

```
Traitify.new.raw_personality_traits("6d28f34b-af14-4fbe-b774-f321fadb5092").first.personality_trait.personality_type.badge.color_1
```

**Comment by efleming** [comment]
Just realized that my above response explains **how** the color is there but not **why**. A personality type is really a collection of personality traits. Our psychology team chooses a color to associate with each personality type, something that reflects that personality type. This allows us to represent traits and types in a more visual way.

**Comment by fredngo** [comment]
Got it. I appreciate your time, thank you!
