### ISSUE TITLE
Traitify::NotFound

### ISSUE THREAD

**Issue by fredngo** [traitify/traitify-ruby#4]
Hey, is the Traitify API down? Over the last day or so I've been getting Traitify::NotFound exceptions:

GET | https://api.traitify.com/v1/assessments/xxxxx/personality_traits/raw | 404 | Nothing found for ids = xxxxx

Thanks!

**Comment by ryanlchandler** [comment]
Hi Fred,

The API is up and we've not had any recent issues.  Typically a 404 means that we are unable to find an assessment to match the ID you provided.  This can occur for a number of reasons:
1. The assessment was created in our sandbox environment but fetched from our production environment (or vice versa).
2. The assessment was created with a different API key than the one used to fetch it.
3.  The ID did not come from Traitify (typically a misunderstanding of how the API functions).

Please take a moment to ensure you've not run into one these issues and let us know if you continue to have trouble.

**Comment by fredngo** [comment]
Thanks Ryan! None of the above unfortunately -- our Traitify integration (using this gem) has been stable since the beginning of the year with no problems at all except this one 404. I'll continue to monitor to see if the situation improves. Thanks.

**Comment by ryanlchandler** [comment]
Sorry to hear that.  I'd be happy to track it down in the logs to get a better idea of what has occurred.  I just need the name of the organization that corresponds to your API Key.

**Comment by fredngo** [comment]
Thanks Ryan, I'd really appreciate that. The name of the organization is "Staffupmed", although I'm not sure the exact version of the name that is registered under your system. Would it help if I paste the public key?

**Comment by ryanlchandler** [comment]
Fred,

No problem at all.  I searched back a few days and only found one assessment throwing 404s in our logs.  The assessment ID starting with "e6c".  This assessment is not complete because it is missing responses for slides 31-40.  This explains the 404 when you try to pull results.  You'll see what I mean if you curl:

https://api.traitify.com/v1/assessments/e6c.../slides

Hope this helps!

**Comment by ryanlchandler** [comment]
I went ahead and checked the logs for the slide updates for that assessment and I only see 4 PUTs and I believe we would typically see 5 PUTs for that deck (49 slides in batches of 10).  Perhaps a networking issue prevented one batch of slide updates.
